### ISSUE TITLE
shortest_path demo not running for me

### ISSUE THREAD

**Issue by pathway** [deepmind/graph_nets#100]
Tried:
https://github.com/deepmind/graph_nets/blob/master/graph_nets/demos/shortest_path.ipynb

Fails in colab:
![image](https://user-images.githubusercontent.com/18753/72701136-1c106a80-3b03-11ea-93ec-1f62eed5ea9e.png)

Using python3.

**Comment by alvarosg** [comment]
Thanks for your message. It seems that Networkx 2.0 has deprecated graph.node, in favor of graph.nodes . We will fix it soon, but in the meantime, please try replacing all:

`.node[` by `.nodes[` and `.node.items()` by `.nodes.items()`

Hope this helps!

**Comment by alvarosg** [comment]
Closing as this has been fixed in the latest release.
