### ISSUE TITLE
Wish to know if Graph Nets can model Graph2Graph encoder decoder network

### ISSUE THREAD

**Issue by yogeshhk** [deepmind/graph_nets#102]
The problem I am working on is about dimension reduction of 2D profiles into 1D curve.
Input is a polygonal geometry (graph) and output is a polyline geometry (graph). So, like Machine Translation, its a Graph2Graph encoder decoder problem. I have data-set of input and output geometries. I am looking for graph2graph neural network architecture which will learn the transformation from input to output.

More details:
- Video: https://lnkd.in/f9Vtv3j  (longish, so for your spare time viewing)
- Presentation: https://lnkd.in/fqbW3np
- Short paper:  https://lnkd.in/fP6MVqZ
- Github repo, source code: https://lnkd.in/fpsNT2P
- My LinkedIn Profile https://www.linkedin.com/in/yogeshkulkarni

**Comment by yogeshhk** [comment]
Even Graph Net does not appear to be correct representation of polygonal geometry. Graph is about topology/connectivity and not about spatial placing. Graph nodes cannot represent points which have coordinates and arcs cannot represent lines which may have lengths (well, arcs can have weights, but not lengths). So need more enriched data structure than graph to solve geometric dimension reduction problem. Any clues?

**Comment by alvarosg** [comment]
Thanks for your message, I am not sure I follow. In principle it is possible to specify node positions in the node features, and properties of the edges in the edge features. This is indeed what was done to model objects such as strings in the original [Interaction Networks paper](https://arxiv.org/abs/1612.00222), where models predicted new positions for were the nodes would nodes move, without changing the number of nodes.

However, if what you are looking for is a good model that goes from a graph to a different graph with a different number of nodes and edges, then my understanding is that there is not yet a canonical way to do this. That would require a much more specific and sophisticated model architecture for the graph generator which would need to be designed and built by the user.

**Comment by yogeshhk** [comment]
Later is what the problem needs. Input polygon (say, longish rectangle) is transformed into a polyline (mid-line). So, input graph has different number of nodes, positions than the output graph.
I am currently creating images out of these inputs and outputs and running simple/cnn/pix2pix encoder decode networks, which seem to learn, but that's not solving the real problem. Learning Geometric transformation is. If you come across any theory, implementation around it, do let me know.

**Comment by alvarosg** [comment]
Sounds good, thanks for the clarification, I am closing this for now, since this is more a research question than a library question :)
