### ISSUE TITLE
Can we run graph nets on TPU?

### ISSUE THREAD

**Issue by GentleZhu** [deepmind/graph_nets#104]
It would be nice to run large scale graph nets on TensorFlow research cloud https://www.tensorflow.org/tfrc. 

Best,
Qi

**Comment by alvarosg** [comment]
Hi! In principle it is possible to run graph nets in TPUs. Currently this only works for models that do not use globals (e.g. `gn.modules.InteractionNetwork`), but soon we will provide a new release that will make the entire library compatible with TPU.

However, there is one other catch: TPUs only work with fixed sized tensors, with shapes known at compilation time, but graphs usually change in number of nodes and edges across batches. So you know to make sure the total number of nodes, edges and graphs per batch is fixed and known at compilation time. There are several strategies to do this, and we will also soon release some utility functions to help in this process.

**Comment by GentleZhu** [comment]
Thanks!
