### ISSUE TITLE
hi,i want to know whether graph nets will add DropEdge in the future like https://github.com/DropEdge/DropEdge

### ISSUE THREAD

**Issue by luyifanlu** [deepmind/graph_nets#114]

**Comment by alvarosg** [comment]
> DropEdge randomly removes a certain number of edges from the input graph at each training epoch, acting like a data augmenter and also a message passing reducer.

It seems like it should be possible to apply drop edge as part of the data generation pipeline, and if that is the case it should be possible to apply it to the data, before it is converted into a `GraphsTuple`.
