### ISSUE TITLE
Compatibility for TF2

### ISSUE THREAD

**Issue by cirpote** [deepmind/graph_nets#115]
Hi all,

first of all, I would like to say that I found the paper and this library extremely useful and with many possible real applications. However, I have a small concern about its compatibility with TF2. I tried to re-adapt the shortest_path.py example with the TF2 framework, but I found several compatibility issues.

Is there an easy way to fix it? thanks in advance

**Comment by alvarosg** [comment]
Thank you for your message. Could you clarify what compatibility issues you are referring to?

There is a TF2 version of the `sort.py` demo in [graph_nets/demos_tf2](https://github.com/deepmind/graph_nets/tree/master/graph_nets/demos_tf2). So I don't anticipate big issues converting the shortest path demo, as the main differences between the demos are the inputs and targets, but not the model.

**Comment by cirpote** [comment]
![Screenshot from 2020-04-23 19-25-10](https://user-images.githubusercontent.com/7804435/80130023-41949080-8598-11ea-8a69-a94fc7274dfa.png)

I am not a big expert in python and TensorFlow in general, but it seems the problem arises in the utils_tf.py, after I call utils_tf.placeholders_from_networkxs() in my main .py file.

thanks for your reply

**Comment by zafarali** [comment]
Hi cirpote, looks like you're trying to use placeholders in TF2 which no longer exist. I highly recommend looking at the notebook in [sort example in Tensorflow 2](https://github.com/deepmind/graph_nets/blob/master/graph_nets/demos_tf2/sort.ipynb).

You will need to remove placeholders completely from your code and pass direct Tensors to your graph networks. Hope this helps!

**Comment by cirpote** [comment]
Now it is working, thanks again.

**Comment by Mistobaan** [comment]
feels like the other demos should be updated as well, specifically the graph_net_basics where even the links to TF1 are not even working (i.e. for unsorted_segment_sum 
https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_sum).
Is this task something good for a pull request? Is the repository committed to drop TF1/py2.7 compatibility?

**Comment by alvarosg** [comment]
Thanks for flagging @Mistobaan , the main problem is that we don't have integration tests for the demos, just for the tests, we will set something up :)

Most of the library works exactly the same in TF2 and TF1, as the library is actually the same, and we thought the only differences (`session.run` calls, and `tf.function`) were covered enough to in the TF2 demo to get some users started, so we favored releasing the actual TF2 compatibility earlier for those users with just one demo, rather than delaying the release to include more demos. We will add more demos in the near future :)

**Comment by alvarosg** [comment]
@Mistobaan With respect to the second question:
* py2 compatibility: We may drop the actual compatibility when keeping both actually becomes a problem. For the demos, it should be ok if they are only Py3 compatible.
* we do plan to keep tf1 compatibility for now.
* With respect to the PR, what do you have in mind specifically?

**Comment by Mistobaan** [comment]
@alvarosg thank you for the quick response. 

for the PR I was thinking just a simple update of the notebook to be fully TF2 runnable with the updated links and imports.

**Comment by alvarosg** [comment]
@Mistobaan Of course, if you want to add a separate GraphNets Basics demo to the TF2 demo folder that covers the existing topics + `tf.function` that could be useful. 

Maybe start by covering only `tf.function`, and then we can incrementally go from there if you are up to the task :)
