### ISSUE TITLE
GraphNetwork model checkpointing method?

### ISSUE THREAD

**Issue by agopal42** [deepmind/graph_nets#123]
How do I checkpoint a GraphNetwork model? I tried using tf.train.Checkpoint but the GraphNetwork class doesn't seem to be trackable object. tf.train.Checkpoint throws the following exception:

ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got <attention.GNGlobal object at 0x7f206c71a438>. If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.

Thanks!

**Comment by alvarosg** [comment]
See #83
