### ISSUE TITLE
GNS framework

### ISSUE THREAD

**Issue by SH-DL-DEM** [deepmind/graph_nets#125]
Where can I find the [ Model code and datasets ] mentioned in this article ''Learning to Simulate Complex Physics with Graph Networks''.

**Comment by alvarosg** [comment]
Thanks you for your message, the code will be open sourced in https://github.com/deepmind/deepmind-research/tree/master/learning_to_simulate in the upcoming weeks.

**Comment by SH-DL-DEM** [comment]
Thanks for your reply
