### ISSUE TITLE
Add multiple node features in networkx graph

### ISSUE THREAD

**Issue by ferreirafabio** [deepmind/graph_nets#14]
Is it possible to add multiple features to a single node to a networkx graph and then pass the graph to the graph net function `utils_np.networkx_to_data_dict()`?

In the documentation this case is not explicitly stated:
https://github.com/deepmind/graph_nets/blob/master/docs/graph_nets.md#utils_npnetworkx_to_data_dictgraph_nx-node_shape_hintnone-edge_shape_hintnone-data_type_hintfloat32

Thank you

**Comment by vbapst** [comment]
Hello,

no, this is not currently supported, as `utils_np.networkx_to_data_dict` will only pull the features contained under the key "features". Moreover the remaining of the graph net library (e.g. the modules) assumes that the node features are single tensors.

You could create several graphs and then concatenate them down the line if that helps.

**Comment by ferreirafabio** [comment]
thank you
