### ISSUE TITLE
how to build an heterogeneous graph network?

### ISSUE THREAD

**Issue by zhou-frank** [deepmind/graph_nets#140]
Hi

Recently, I read the paper "[LEARNING MESH-BASED SIMULATION WITH GRAPH NETWORKS](https://openreview.net/forum?id=roNqYL0_XP)".In this paper, the author use two type of edge to pass message , which contain mesh-space and world-space.

How to use graph_nets lib to build this heterogeneous graph network above?

Many thanks for helping me.

**Comment by alvarosg** [comment]
Thanks for your message. The graph nets library does not currently support heterogeneous graphs in a single `GraphsTuple`.

The simple option would be to keep two `GraphsTuple`s one with each of the types of edges, and with the same nodes. And then use the `blocks.broadcasters/aggregator` ops to build a model similar to the existing `blocks.NodeUpdate` and blocks.EdgeUpdate` that operates on both graphs in parallel.

Some options:
* I suspect the model may also work if you simply merge all edges into a single type, if all you are looking for informal reproducibility.
* At the edge update, you may want to use two separate MLPs for each edge type, by storing the edge type, then mask out the outputs corresponding to the wrong type for each MLP, and concatenate them side by side.
* Implementing the exact same baseline in an efficient way would require using the low level API of the GraphNets library as indicated above.

**Comment by zhou-frank** [comment]
@alvarosg thanks for your help.I will try to implement your advise approach.

Besides, may i ask you a question? When will you publish the code of the paper?

**Comment by alvarosg** [comment]
Code is now available here https://github.com/deepmind/deepmind-research/tree/master/meshgraphnets :)
