### ISSUE TITLE
Error while using the placeholder function from utils_tf

### ISSUE THREAD

**Issue by Krishuthapa** [deepmind/graph_nets#149]
Issue: 
I am using the graph_nets library with tf2. I am trying to use `utils_tf.placeholders_from_networkxs()` this function to create the placeholders for my graphs to implement the EncodeProcessDecode feature. However , I am getting the following message with this:

```
module 'tensorflow' has no attribute 'placeholder'
```

Aren't the functions in the utils file compatible with the tensorflow v2?

**Comment by alvarosg** [comment]
Thanks for your comment! 

Actually the concept of `tf.placeholder` was associated with `tf.Session`, and both were removed in TensorFlow 2. I would recommend looking at the [TensorFlow 2 demos](https://github.com/deepmind/graph_nets/tree/master/graph_nets/demos_tf2) for some examples of how to use the library without `tf.Session`.
