### ISSUE TITLE
Understand Some Physics Demo Constants

### ISSUE THREAD

**Issue by IMBurbank** [deepmind/graph_nets#20]
I'm working through the demos to inform my approach to a graph problem, but there are two constants in the physics example that I don't understand. I was hoping you could provide a bit of context.

Both are in the `base_graph` function. 

I can't find any physical analog to this constant number `5`.
```python
nodes = np.zeros((n, 5), dtype=np.float32)
```

Or for this globals `0`.
```python
return {
    "globals": [0., -10.],
    ...
}
```

**Comment by IMBurbank** [comment]
I think the `5` represents the 5 node attributes used in the simulation `[x, y, v_x, v_y, is_fixed]`. If that's correct, I'm almost there on understanding the demo setup. I'm still looking for a hint of there the globals `0` comes from.

**Comment by ctessum** [comment]
I think `"globals": [0., -10.]`  means that acceleration due to gravity is 0 m/s^2 in the x-direction and 10 m/s^2 in the y-direction. Not sure why they didn't use 9.8 instead of 10.

**Comment by IMBurbank** [comment]
Thanks. That's what I was thinking but, since gravity can be expressed with one-dimension, I couldn't be sure it wasn't representing another property.
