### ISSUE TITLE
Memory leak running in eager mode

### ISSUE THREAD

**Issue by mmv** [deepmind/graph_nets#23]
In eager execution mode, running or training GN models results in a memory leak.

Simple code to reproduce issue:

    import tensorflow as tf
    import numpy as np
    import graph_nets
    import networkx as nx
    from graph_nets.demos.models import EncodeProcessDecode

    # Enable eager exec
    tf.enable_eager_execution()

    # Create some dummy graphs and fill with random data
    graphs = []
    for gi in range(50):
        g = nx.geographical_threshold_graph(20, 30)
        g.graph['features'] = np.zeros([1], dtype=float)
        for node_index, node_feature in g.nodes(data=True):
            g.add_node(node_index, features=np.random.rand(3))
        for s,t,f in g.edges(data=True):
            g.add_edge(s,t, features=np.random.rand(3))
        
        graphs.append(g)

    xs = graph_nets.utils_np.networkxs_to_graphs_tuple(graphs)

    # network needs tensors, not numpy
    xs = xs.map(lambda a: tf.constant(a), fields=graph_nets.graphs.ALL_FIELDS)

    model = EncodeProcessDecode(edge_output_size=3, node_output_size=3)

    # execution loop, reusing the same model and same data
    # with each iteration, the memory usage increases and is never collected
    for i in range(1000):
        if i % 10 == 0: print("step:", i)
        model(xs, num_processing_steps=2)

In graph execution mode the memory leak doesn't happen.

Relevant package versions:

    tensorflow-gpu==1.12.0
    tensorflow-probability-gpu==0.4.0
    dm-sonnet==1.23
    graph-nets==1.0.2

**Comment by mmv** [comment]
I verified that this doesn't happen if I force `graph_nets` to run against the latest `sonnet` (1.27).

So on one hand this is a sonnet issue (rather than a graph_nets issue). On the other hand, having `graph_nets` to require an outdated version is the current cause of this problem, so at least that should be fixed.

**Comment by ywangeq** [comment]
@mmv  I also face this problem. I guess this is due the graph create the tensor each iteration in the training in eager. Have you solved this? The change version method doesn't work for me

**Comment by mmv** [comment]
@ywangeq for me upgrading sonnet was enough to fix the issue.

In the meanwhile I also made a port of the code as-is from sonnet layers to tf.keras layers, which is what I've been using. Because it's tf.keras, it'll tend to keep up with tensorflow novelties so it works under eager mode and doesn't require me to learn about an additional library (sonnet). If upgrading sonnet doesn't cut it you may try this port [here](https://github.com/OutSystems/graph_nets/tree/tf-keras) or with pip install from `git+https://github.com/OutSystems/graph_nets.git@tf-keras`

**Comment by ywangeq** [comment]
@mmv Thanks. The newest version of sonnet solved my problem.

**Comment by alvarosg** [comment]
Closing since #64 was submitted and should fix this.
