### ISSUE TITLE
Hi, you are feeding numpy data into your graph.

### ISSUE THREAD

**Issue by luyifanlu** [deepmind/graph_nets#26]
You should do 
```
input_graphs = utils_tf.data_dicts_to_graphs_tuple([data_dic])
```

_Originally posted by @vbapst in https://github.com/deepmind/graph_nets/issues/6#issuecomment-441012833_

**Comment by alvarosg** [comment]
[Run "graph nets basics demo" in browser](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb)

The new "graph nets basics demo" is a tutorial containing step by step examples about how to create and manipulate graphs, how to feed them into graph networks and how to build custom graph network modules.
