### ISSUE TITLE
Install tensorflow_probability_gpu always crush all tensorflow

### ISSUE THREAD

**Issue by LingxiaoShawn** [deepmind/graph_nets#30]
I'm using ubuntu 18.04 with cuda 9.2. 
And I can easily install tensorflow-gpu using conda as well as install graph-nets using pip. And 
after install all library works fine with my gpu. (cuda9.2 + nvidia_diver 396) 
However, once I installed tensoflow-probability-gpu, everything just crushed. 
I got the following error for importing any tensorflow related library. 

ImportError: lincublas.so.9.0: cannot open shared object file: No such file or directory.

It seems tensorflow-probability-gpu library doesn't support cuda9.2.

Any idea for installing this library? 

Thanks.

**Comment by mmv** [comment]
The latest `tensorflow-probability` (0.5.0) works for both CPU and GPU tensorflow variants and no longer has a direct install dependency for tensorflow packages, so it shouldn't cause your existing packages to be downgraded or replaced.
