### ISSUE TITLE
Using TFRecords for Data loading

### ISSUE THREAD

**Issue by stephenphillips42** [deepmind/graph_nets#49]
I have been trying to make TFRecords work with GraphNets but I haven't been able to make it work. All the code for this relies on generating graphs on the fly to numpy arrays - I need to load my data from disk (hence I want the speed that TFRecords give). Is there any way to do this, or do I have to write a new data loader for this?

**Comment by alvarosg** [comment]
Closing this issue as @stephenphillips42 started creating [this library](https://github.com/stephenphillips42/tf_data_loader) for this use case. Thanks Stephen!
