### ISSUE TITLE
Motivation for concatenation of states in EncodeProcessDecode's core

### ISSUE THREAD

**Issue by ferreirafabio** [deepmind/graph_nets#56]
Hi, what is the motivation behind concatenating the encoder's output with the previous output of the core in the `EncodeProcessDecode` model given in the examples?

Neither in the graph nets paper I can find this information nor in the respective comment block in the code this information is given:

```
    - ...
    - A "Core" graph net, which performs N rounds of processing (message-passing)
    steps. The input to the Core is the concatenation of the Encoder's output
    and the previous output of the Core (labeled "Hidden(t)" below, where "t" is
    the processing step).
    - ...

                      Hidden(t)   Hidden(t+1)
                         |            ^
            *---------*  |  *------*  |  *---------*
            |         |  |  |      |  |  |         |
  Input --->| Encoder |  *->| Core |--*->| Decoder |---> Output(t)
            |         |---->|      |     |         |
            *---------*     *------*     *---------*
    """
```

**Comment by vbapst** [comment]
Hi Fabio,

this is similar to a skip connection an helps stabilize training. Moreover in the beginning when your core is random, applying it many times will wash out most of information from the input. Skip-connecting the encoded input at every step helps propagate information to the decoder and initiate learning.
