### ISSUE TITLE
Batch processing with list of lists of input and ground truth graphs

### ISSUE THREAD

**Issue by ferreirafabio** [deepmind/graph_nets#58]
Hi, 
to my best knowledge, the graph net examples don’t show how to process list of lists of graphs as batches. Here's an example to provide more details:

I have created lists of `GraphsTuple` that have shape:
```
input_graph: (1,)
target_graphs: (10,)
```

If I stack these single examples (say batch_size=20), I get the following:
```
input_graphs: (20, 1)
target_graphs: (20, 10)
```
Batch processing is possible for a list of graphs (I've been using this so far with `utils_tf.placeholders_from_networkxs()` that takes lists [but not nested lists] as input). How can batch processing now be done with list of lists?
Using `utils_tf.placeholders_from_networkxs()` for every single example will yield placeholders with duplicate names as far as I know? This in turn makes it impossible to assemble the feed_dict for the sess.run() since the uniqueness of names is not given and the dict will collapse to a single example.

To illustrate this, here's a code example for the single sample case (shapes input_graphs (1,), target_grpahs (10,)):
```
input_ph = utils_tf.placeholders_from_networkxs(input_graphs, force_dynamic_num_graphs=True)
target_ph = utils_tf.placeholders_from_networkxs(target_graphs[0], force_dynamic_num_graphs=True)

input_tuple = utils_np.networkxs_to_graphs_tuple([input_graphs])
target_tuple = utils_np.networkxs_to_graphs_tuple(target_graphs) <--- how to deal with list of lists?

input_dct = utils_tf.get_feed_dict(input_ph, input_tuple)
target_dct = utils_tf.get_feed_dict(target_ph, target_tuple)

return {**input_dct, **target_dct}
```

Is there something I am missing? Thank you.

**Comment by vbapst** [comment]
I think you should take care of flattening everything in a single list (keeping track of the original structure) and then unflatten after you've processed your data. The library does not offer support for arbitrary nests of graphs at the moment.

**Comment by alvarosg** [comment]
Closing assuming the last answer solved the problem due to inactivity. Please feel free to reopen if necessary.
