### ISSUE TITLE
Changing edges in the model

### ISSUE THREAD

**Issue by FilippNikitin** [deepmind/graph_nets#60]
Hello,
I want to solve my task using the library. In my problem, the source graph and target graph has the same nodes but some edges are different.  And I want to predict the changes. As I understood, the only manipulation with edges, nodes and global features is supported. Am I right?
Thank you in advance!

**Comment by vbapst** [comment]
I guess the wider question here is what kind of learning algorithm do you plan to use?
You could for instance fully connect your initial graph, adding a marker for the edges in the source graph, and then try to predict the edges that are different in the target graph ?

**Comment by FilippNikitin** [comment]
@vbapst 
Thank you so much for your answer. I've had the same idea as yours (using fully connected graphs), but I haven't checked the approach.

**Comment by alvarosg** [comment]
Closing assuming the last answer solved the problem due to inactivity. Please feel free to reopen if necessary.
