### ISSUE TITLE
Understanding EncodeProcessDecode

### ISSUE THREAD

**Issue by czhang0528** [deepmind/graph_nets#62]
Thanks for your wonderful work! I have some concerns on the implementation of EncodeProcessDecode().

For a 'one-layer' full GN block (i.e., num_processing_steps=1), we will train three networks, say edge_net, node_net, and global_net.

When we set 'num_processing_steps=2' in EncodeProcessDecode(). The second time we call 'latent = self._core(core_input)', it seems that we will train the second edge_net, node_net, and global_net. Those two layers GNs do not share parameters. Is that right? 

So how can I keep turning the first layer GN on the second step, but not creating three additional networks? (As shown in Fig. 6 of your GNNs paper)

**Comment by vbapst** [comment]
Hi,

no, parameters are shared between the different processing steps, as we are reusing `self._core`.

**Comment by alvarosg** [comment]
Closing assuming the last answer solved the problem due to inactivity. Please feel free to reopen if the problem persists.
