### ISSUE TITLE
Why is the dm-sonnet version pinned?

### ISSUE THREAD

**Issue by timokau** [deepmind/graph_nets#63]
Currently the `dm-sonnet` dependency is pinned to version 1.23:
https://github.com/deepmind/graph_nets/blob/530aeadbc686f436e907ca8d111b5a72788906ee/setup.py#L40
Is there a reason for it? I tried lifting that restriction and at least the shortest path example executes without issues with `dm-sonnet` 1.30.

**Comment by alvarosg** [comment]
Thanks for pointing this out. This was done to temporarily circumvent an upstream bug [context](https://github.com/deepmind/graph_nets/issues/2). We will un-pin it shortly.

**Comment by alvarosg** [comment]
This [PR](https://github.com/deepmind/graph_nets/pull/64) should fix it.

**Comment by alvarosg** [comment]
Closing since #64 was submitted and should fix this.
