### ISSUE TITLE
attributes error- graph_nets_basics issue

### ISSUE THREAD

**Issue by JenZ2019** [deepmind/graph_nets#68]
When running the graph_nets_basics.ipynb on Colab, the following code got AttributeError.  Thanks.

```
tf.reset_default_graph()
graph_network = modules.GraphNetwork(
    edge_model_fn=lambda: snt.Linear(output_size=10),
    node_model_fn=lambda: snt.Linear(output_size=15),
    global_model_fn=lambda: snt.Linear(output_size=20))

input_graphs = utils_tf.data_dicts_to_graphs_tuple(graph_dicts)
output_graphs = graph_network(input_graphs)

for var in graph_network.variables:
  print(var)
```

> AttributeErrorTraceback (most recent call last)
> <ipython-input-56-b42ca5c29bb0> in <module>()
>       8 output_graphs = graph_network(input_graphs)
>       9 
> ---> 10 for var in graph_network.variables:
>      11   print(var)
> 
> AttributeError: 'GraphNetwork' object has no attribute 'variables'

**Comment by alvarosg** [comment]
Thank you for pointing this out. 

I think this issue may be related to the fact that the library is currently pinned to sonnet v1.23 (see [issue](https://github.com/deepmind/graph_nets/pull/64)).

This is in the process of being fixed, but you may try upgrading sonnet manually in the meantime:
`pip install dm-sonnet --upgrade` 
(or `!pip install dm-sonnet --upgrade` if you are in Colaboratory).

Alternatively you may use `graph_network.get_variables()`.

Hope this helps!

**Comment by JenZ2019** [comment]
It works! Thanks!
