### ISSUE TITLE
Can GN handle text data?

### ISSUE THREAD

**Issue by JenZ2019** [deepmind/graph_nets#71]
Hello, can GN handle the logic reasoning on text data? Currently, all demos are for computing numbers.

**Comment by vbapst** [comment]
Can you be a bit more specific about what you want to do?

Graphs nets make no assumption about the type of their inputs/outputs nor of the processing models being used, and they can be used for language reasoning, but we would need a bit more details to give you a more precise answer.

**Comment by JenZ2019** [comment]
Thank you for your reply. For example, inputs a social network,  where nodes represent person with text-based attributes. By applying some laws in the processing models (eg, compare some text-based attributes of nodes) to output the network graph with the updated relations.
