### ISSUE TITLE
NameError: name 'utils_np' is not defined

### ISSUE THREAD

**Issue by priyeshshukla** [deepmind/graph_nets#72]
Hi, while going through graph_nets_basics tutorial in colab, I get the following error while putting the graph dictionaries into a GraphsTuple using utils_np.data_dicts_to_graphs_tuple. I could not get a clear solution to it anywhere. Help is appreciated.

NameErrorTraceback (most recent call last)
<ipython-input-3-d142be54bb97> in <module>()
      1 data_dict_list = [data_dict_0, data_dict_1]
----> 2 graphs_tuple = utils_np.data_dicts_to_graphs_tuple(data_dict_list)

NameError: name 'utils_np' is not defined

**Comment by vbapst** [comment]
Hello,

did you run the cells above in the colab (in particular, the third cell that contains the `utils_np` import)?

**Comment by priyeshshukla** [comment]
Hello, yeah I was directly running the cells in colab. Later, I imported all required imports separately first, it worked. Thanks!
