### ISSUE TITLE
tensorflow_gpu tensorflow_probability_gpu

### ISSUE THREAD

**Issue by luyifanlu** [deepmind/graph_nets#74]
if my library both have tensorflow_gpu tensorflow_probability_gpu and tensorflow tensorflow_probability.how to make sure i use gpu

**Comment by alvarosg** [comment]
You may be able to use some of the approaches proposed here:
https://github.com/keras-team/keras/issues/6997

**Comment by alvarosg** [comment]
Closing assuming the last answer solved the problem due to inactivity. Please feel free to reopen if necessary.
