### ISSUE TITLE
How to stack the global/node features of a GraphsTuple over batch axis

### ISSUE THREAD

**Issue by ronsoohyeong** [deepmind/graph_nets#76]
Hi
I am trying to feed a GraphsTuple tensor, which results from passing through the modules, to a downstream model, and I wonder how I can stack the global or node features of the GraphsTuple to a tensor with the shape of either (batch size, global feature dimension) or (batch size, number of nodes, node feature dimension) respectively.

It seems I need to first slice the GraphsTuple and stack, but I hope you may enlighten me how to exactly do it by a concrete example or tutorial.

Best regards,
Ron

**Comment by alvarosg** [comment]
You should be able to use `utils_tf.concat(..., axis=0)` to batch multiple graph tuples.

https://github.com/deepmind/graph_nets/blob/0f4d0603400cfbb73968c1b653273d1d8ffa0c8f/graph_nets/utils_tf.py#L350

**Comment by ronsoohyeong** [comment]
Thanks for the reply. I've realized that the concatenation of graphs is done by forming a disconnected graph for the nodes and edges, while the globals, n_nodes, and n_edges are concatenated over the batch axis.
