### ISSUE TITLE
How to use modules.SelfAttention

### ISSUE THREAD

**Issue by ronsoohyeong** [deepmind/graph_nets#77]
Hi
I tried to use modules.SelfAttention like this:
`graph_network = modules.SelfAttention()`
`input_graphs = utils_tf.data_dicts_to_graphs_tuple(graph_dicts)`
`output_graphs = graph_network(input_graphs)`

Then, I get this error:
`TypeError: _build() missing 3 required positional arguments: 'node_keys', 'node_queries', and 'attention_graph'`

I wonder if there's a notebook explaining how to use the modules.SelfAttention.

Best regards,
Ron

**Comment by alvarosg** [comment]
Hi Ron,

The SelfAttention module receives four different arguments, documented [here](https://github.com/deepmind/graph_nets/blob/6f33ee4244ebe016b4d6296dd3eb99625fd9f3af/graph_nets/modules.py#L629). There is also an example of usage in the corresponding [test](https://github.com/deepmind/graph_nets/blob/6f33ee4244ebe016b4d6296dd3eb99625fd9f3af/graph_nets/tests/modules_test.py#L1162).

Hope this helps, but let me know if you have more questions.

**Comment by ronsoohyeong** [comment]
Thanks. I was able to make it work.
