### ISSUE TITLE
EncodeProcessDecode model is not working with graphs without edges

### ISSUE THREAD

**Issue by dibyendu** [deepmind/graph_nets#78]
I have got a set of labeled graphs without any edges. I want to train an `EncodeProcessDecode` model with these graphs. I'm following these basic instructions to encode my [graphs without edges](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb#scrollTo=efQtkXoFr5su). I am also following the [shortest path demo](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/shortest_path.ipynb) to use the `EncodeProcessDecode` model for training.

Here is the relevant portion of my code.

```python
import numpy as np
from graph_nets import utils_np
from graph_nets import utils_tf
from graph_nets.demos import models

# Node features.
input_nodes_1 = np.array([[10, 2, 1], [11, 1, 0], [12, 1, 3]])
input_graph_1 = {
   "globals": np.array([0.0]),
    "nodes": input_nodes_1,
}

target_nodes_1 = np.array([[1, 0], [0, 1], [1, 0]])
target_graph_1 = {
   "globals": np.array([0.2]),
    "nodes": target_nodes_1,
}
    
graphs_ph = utils_tf.placeholders_from_data_dicts([input_graph_1, target_graph_1])

graphs_tuple = utils_np.data_dicts_to_graphs_tuple([input_graph_1, target_graph_1])

feed_dict = {graphs_ph: graphs_tuple}

model = models.EncodeProcessDecode(edge_output_size=None, node_output_size=2)

# A list of outputs, one per processing step.
output_graphs = model(graphs_ph, 20)  # 20 `GraphsTuple` objects
```

But the last line seems to cause an `AttributeError: 'NoneType' object has no attribute 'get_shape'`.

Here is the initial portion of a rather long Traceback 
```
  File "/home/dibyendu/anaconda3/envs/pyvenv2/lib/python2.7/site-packages/graph_nets/demos/models.py", line 39, in make_mlp_model
    snt.nets.MLP([LATENT_SIZE] * NUM_LAYERS, activate_final=True),
  File "/home/dibyendu/anaconda3/envs/pyvenv2/lib/python2.7/site-packages/sonnet/python/modules/nets/mlp.py", line 85, in __init__
    super(MLP, self).__init__(custom_getter=custom_getter, name=name)
  File "/home/dibyendu/anaconda3/envs/pyvenv2/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 180, in __init__
    custom_getter_=self._custom_getter)
  File "/home/dibyendu/anaconda3/envs/pyvenv2/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)
```

Seems like this model is **not working with graphs without edges**. In that case, what model should I use for such graphs?

Does anyone have any idea?

Thanks,

**Comment by alvarosg** [comment]
Hi @dibyendu,

If your graphs don't have edges (i.e. they are sets), then you have two options:
1. If you truly want to work just purely with sets, then there are only 2 pre-built graph network modules modules that are fully compatible with graphs without edges: `graphs.modules.GraphIndependent` with `edge_model_fn` set to `None` , and `graphs.modules.DeepSets`. You would have to modify `EncodeProcessDecode` replacing  the `modules.GraphNetworks` by `Deepsets`. Please bear in mind that `DeepSets` does not do pairwise relational reasoning.

2. If you want to use a model with pairwise relational reasoning. Then the easiest thing to do is to add edges to your input graphs, and because I assume that you would not have a prior on which edges should be added, best thing you can do is to fully connect your graph, and add some dummy zero features. You can do this directly in the tensorflow graph:
```
input_graphs = utils_tf.fully_connect_graph_dynamic(graphs_ph)
input_graphs = utils_tf.set_zero_edge_features(input_graphs, 1)
output_graphs = model(input_graphs, 20)  # 20 `GraphsTuple` objects
```
Or you could directly create your data to be fully connected (which may be a bit faster). Please take into account that this will create a quadratic number of edges, so if your graphs have a large number of nodes, this may increase memory requirements quickly.

Hope this helps!

**Comment by dibyendu** [comment]
@alvarosg, thanks for the help. I'm looking into your suggestions.

Just to let you know, I've already tried with a complete graph (every node is connected to every other node),  on the `EncodeProcessDecode` model but the accuracy being very low, I was thinking of working with the isolated-node graph (without any edges) this time.

Here is what my dataset looks like:

A set of N data points, each of which is a 2D cartesian plane of dimension 1024 x 1024 (say). In each plane, there are some points marked as class-0 (x) and some points marked as class-1 (o). A simple diagram below.

```
    data point #1
    
            (0,1024)                          (1024,1024)
                |--------------------------------|
                |          x                     |
                |        xx                      |
                |         x                      |
                |        x    o                  |
                |              x                 |
                |         x      x               |
                |                  o             |
                |                                |
                |                                |
                |                                |
                ----------------------------------
               (0,0)                           (1024,0)
    
    data point #2
    
            (0,1024)                          (1024,1024)
                |--------------------------------|
                |                                |
                |        xo                      |
                |         o                      |
                |        x                       |
                |                                |
                |         x                      |
                |                  o             |
                |                   xxx          |
                |                                |
                |                                |
                ----------------------------------
               (0,0)                           (1024,0)
    .
    .
    .
     data point #N

            (0,1024)                          (1024,1024)
                |--------------------------------|
                |                                |
                |        xo                      |
                |         o                      |
                |        x                       |
                |                                |
                |         x                      |
                |                  o             |
                |                   xox          |
                |                       x        |
                |                     x          |
                ----------------------------------
               (0,0)                           (1024,0)
```

Points marked as class-1 (o) are the minority. We know the cartesian coordinates (x,y) of every single point as their labels (class-0/class-1) as well.

I want to be able to make predictions for an unlabeled plane of points like this.

```
    unknown data point
    
            (0,1024)                          (1024,1024)
                |--------------------------------|
                |          .                     |
                |        ..                      |
                |         .                      |
                |        .                       |
                |       .                        |
                |      .                         |
                |                  .             |
                |                                |
                |                ..              |
                |               .                |
                ----------------------------------
               (0,0)                           (1024,0)

```

My idea was to convert the coordinates into nodes of a graph (either complete or edge less) and use the `EncodeProcessDecode` model on those graphs. But the accuracy was very low for complete graphs. Hence I was thinking of working with sets this time.

I would really appreciate if you can put some remark on how to model these plane of points into graphs and what graph-network I should use to get a decent result.

Thanks again.
