### ISSUE TITLE
Could not find a version that satisfies the requirement graph_nets

### ISSUE THREAD

**Issue by lyyang233** [deepmind/graph_nets#8]
pip install graph_nets

Collecting graph_nets
  Could not find a version that satisfies the requirement graph_nets (from versions: )
No matching distribution found for graph_nets

**Comment by nishnash54** [comment]
Try this

```pip install graph-nets```

[graph-nets - PyPI](https://pypi.org/project/graph-nets/)

**Comment by lyyang233** [comment]
Thank you for the suggested fix.
