### ISSUE TITLE
RDF data input

### ISSUE THREAD

**Issue by namedgraph** [deepmind/graph_nets#87]
Hi,

what are the supported graph data formats? Can [RDF graphs](https://www.w3.org/RDF/) be used as input?

**Comment by alvarosg** [comment]
Or all of our library modules operate on our data-structure `GraphsTuple`. In `utils_np` and `utils_tf` we provide util functions to convert from other formats, of which the most well known is `networkx`. Specifically we support `networkx.OrderedMultiDiGraph`, where the keys to the nodes are integer numbers from `0` to `num_nodes - 1`.

Based on a [quick search](https://stackoverflow.com/questions/57167764/can-networkx-library-read-rdf-data-in-ntriple-format-and-build-a-graph-object-al) it seems that there are simple ways to convert from RDF graphs to networkx graphs. 

You would need to be careful to re-index the nodes to satisfy the key constraint specified above if required, and also store the node, edge and global features in a key named "features" (as in our [examples](https://github.com/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb).

But beyond small data conversion it should be quite straight forward.

Hope this helps!
