### ISSUE TITLE
Typo in docstring

### ISSUE THREAD

**Issue by tamuhey** [deepmind/graph_nets#9]
https://github.com/deepmind/graph_nets/blob/61a0f055d5892c014260f784ee4fb59e2ba11607/graph_nets/tests/modules_test.py#L193

I think "InteractionNetwork" should be replaced to "GraphIndependent".

**Comment by alvarosg** [comment]
Thank you for pointing this out, it has now been fixed in our internal version, and will reflect in github after the next release.
