### ISSUE TITLE
 neural-structured-learning

### ISSUE THREAD

**Issue by boraturant** [deepmind/graph_nets#95]
Hi,

It would be great if  Graphnet people can comment on the new Tensorflow  Neural-Structured-Learning project (https://github.com/tensorflow/neural-structured-learning). 

Would be helpful for future direction decisions in our projects.

Thanks

**Comment by alvarosg** [comment]
Thanks! for your message. My understanding is that there is yet not too much overlap between the actual functionality provided by the Neural-Structured-Learning project and the GraphNets library.
