### ISSUE TITLE
I'd like to know how to use graph_nets make a Hyperbolic Graph Convolutional Networks .

### ISSUE THREAD

**Issue by luyifanlu** [deepmind/graph_nets#97]

**Comment by luyifanlu** [comment]
can you add add an example for it

**Comment by luyifanlu** [comment]
can you add  an example for it

**Comment by RexYing** [comment]
Hi I think it should be easy to adapt.

The original message computation in EdgeBlock is the concatenation of source and target node features and the edge features through an MLP. 
For hyperbolic GCN, this function should be replaced by another function that first maps the source node to the tangent space of the target node, and then pass through an MLP. 
This could be written in broadcast_receiver_nodes_to_edges function.

The aggregation part does not need to be changed. 
Lastly the update step (line 459 of blocks.py): pdated_edges = self._edge_model(collected_edges)
Here you need to map the collected edges back to the hyperbolic space through exp map.
