### ISSUE TITLE
Regularization in Sonnet2

### ISSUE THREAD

**Issue by maguileracanon** [deepmind/graph_nets#98]
I wanted to implement the regularizer modules available in Sonnet 2, but this seems to be built on top of Tensorflow 2. 
Does the current version of graph_nets supports Sonnet 2?. 
thanks 
Mara

**Comment by alvarosg** [comment]
Thanks for your message!

The library does not yet officially support TF2/Sonnet2, we are testing it internally and will release TF2/Sonnet2 support early next year (hopefully within a month).

I will leave this open in the meantime. Hope this helps!

**Comment by alvarosg** [comment]
Closing as the library is now compatible with TensorFlow2 and Sonnet2 :)
