### ISSUE TITLE
module 'tensorflow' has no attribute 'GraphKeys'

### ISSUE THREAD

**Issue by sonofaeolus** [deepmind/graph_nets#99]
>>> import sonnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/.pyenv/versions/tf20/lib/python3.5/site-packages/sonnet/__init__.py", line 67, in <module>
    from sonnet.python import custom_getters
  File "/home/work/.pyenv/versions/tf20/lib/python3.5/site-packages/sonnet/python/custom_getters/__init__.py", line 26, in <module>
    from sonnet.python.custom_getters.restore_initializer import restore_initializer
  File "/home/work/.pyenv/versions/tf20/lib/python3.5/site-packages/sonnet/python/custom_getters/restore_initializer.py", line 27, in <module>
    collection=tf.GraphKeys.GLOBAL_VARIABLES):
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'
>>> module 'tensorflow' has no attribute 'GraphKeys'
import error, my tensorflow version is 2.0.0b0 and my tensorlayer version is 2.1.0 
how can i fix it?

**Comment by vbapst** [comment]
I believe that this is due to your sonnet version being sonnet v1 while you are using tensorflow 2 (https://github.com/deepmind/sonnet). Note that our library is not yet compatible with tensorflow 2 (but will soon be).

**Comment by sonofaeolus** [comment]
another question which graph-nets version supports tensorflow 1.14

**Comment by sonofaeolus** [comment]
> 
> 
> I believe that this is due to your sonnet version being sonnet v1 while you are using tensorflow 2 (https://github.com/deepmind/sonnet). Note that our library is not yet compatible with tensorflow 2 (but will soon be).

thanks

**Comment by alvarosg** [comment]
Version 1.0.4 of the GraphNets library should be compatible with tensorflow 1.14 .

**Comment by sonofaeolus** [comment]
> 
> 
> Version 1.0.4 of the GraphNets library should be compatible with tensorflow 1.14 .

version 1.0,3 is compatible with tensorflow 1.14. thanks
